version: '3.6'

services:

  # Hasura
  hasura:
    image: hasura/graphql-engine:v2.35.1
    ports:
    - "8080:8080"
    depends_on:
    - pg_hasura
    - keycloak
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@pg_hasura:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey # comment out to make admin console public
      # un-comment the following line to activate JWT Authentication:
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "RS256", "claims_namespace": "https://hasura.io/jwt/claims", "claims_format": "json", "key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwzWxgpauMX01W7grvAHG481M6eLPdJQ/+SU3pOHPpXMbdRNNRcwb9lPR+BIekhxJL2ySdBC/u+QHjIXaBHpO9KUMEe/N4KkMp15Jxcfdr56L9GPfeRIj9OnB21yQIDdPxfrfo9cL2Wp5VyCqvaprZVD/PFQV4iEd0jc+WsYHToY3HihhMWGrDWFO3QCSWZNPIpqmzVm+8SH3iYuKrVrXeAsVn0BXLtHodW6oWhIHJjgEXB8qMljwhGN3Dn6FdDjDhqZq0YqpRIKI6c4f5+hsX+gB4BWW2zIAy0XB8tFflVwgCE4XjGHacvvgXeHRyZGSkgah6gBNMvLve1pi2+UMqQIDAQAB\n-----END PUBLIC KEY-----" }'

  # PostgreSQL Server for Hasura
  pg_hasura:
    image: postgres:15
    volumes:
    - pg_hausra_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    ports:
      - "8081:8080"
    command: start-dev --features='scripts'
    depends_on:
      - pg_keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_DB_URL_HOST=pg_keycloak

  # PostgreSQL Server for Keycloak
  pg_keycloak:
      image: postgres:15
      volumes:
        - pg_keycloak_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

volumes:
  pg_hausra_data:
  pg_keycloak_data:
